const NAVIGATION = [
  {
    id: 1,
    category: "SHOP",
    subcategory: [
      { id: 1, title: "BESTSELLERS" },
      { id: 2, title: "ONLINE SPECIALS" },
      {
        id: 3,
        title: "BAGS",
        options: [
          { id: 1, title: "ALL MODELS" },
          { id: 2, title: "BACKPACKS" },
          { id: 3, title: "MESSENGER" },
          { id: 4, title: "SHOPPER" },
          { id: 5, title: "SHOULDER BAGS" },
          { id: 6, title: "TOTE BAGS" },
          { id: 7, title: "LAPTOP BAGS" },
          { id: 8, title: "TRAVEL BAGS" },
          { id: 9, title: "SPORTS BAGS" },
        ],
      },
      {
        id: 4,
        title: "ACCESSORIES",
        options: [
          { id: 1, title: "ALL MODELS" },
          { id: 2, title: "WALLETS" },
          { id: 3, title: "CASES & SLEEVES" },
          { id: 4, title: "POUCHES" },
          { id: 5, title: "AGENDAS & NOTEBOOKS" },
          { id: 6, title: "TOILETRY BAG" },
          { id: 7, title: "KEYHOLDERS" },
          { id: 8, title: "SHOULDER PADS" },
          { id: 9, title: "BOOKS & STUFF" },
        ],
      },
      {
        id: 5,
        title: "APPAREL FEMALE",
        options: [
          { id: 1, title: "ALL MODELS" },
          { id: 2, title: "T-SHIRTS" },
          { id: 3, title: "DRESS / SKIRT" },
          { id: 4, title: "PANTS" },
          { id: 5, title: "SHIRTS" },
          { id: 6, title: "SWEATSHIRTS" },
          { id: 7, title: "JACKETS" },
          { id: 8, title: "APRON" },
        ],
      },
      {
        id: 6,
        title: "APPAREL MALE",
        options: [
          { id: 1, title: "ALL MODELS" },
          { id: 2, title: "T-SHIRTS" },
          { id: 3, title: "TANK TOP" },
          { id: 4, title: "SHIRTS" },
          { id: 5, title: "PANTS" },
          { id: 6, title: "SWEATSHIRTS" },
          { id: 7, title: "JACKETS" },
          { id: 8, title: "APRON" },
        ],
      },
      { id: 7, title: "VOUCHER" },
    ],
  },
  {
    id: 2,
    category: "STORIES",
    subcategory: [
      { id: 1, title: "NEWS" },
      { id: 2, title: "FRIENDS & PROJECTS" },
      { id: 3, title: "OUR MATERIALS" },
      { id: 4, title: "ABOUT FREITAG" },
    ],
  },
  { id: 3, category: "CITY GUIDE LINES" },
  {
    id: 4,
    category: "S.W.A.P.",
    subcategory: [
      { id: 1, title: "START S.W.A.P" },
      { id: 2, title: "ABOUT S.W.A.P" },
    ],
  },
  {
    id: 5,
    category: "CONNECT",
    subcategory: [
      { id: 1, title: "NEWSLETTER" },
      { id: 2, title: "EVENTS" },
      { id: 3, title: "PRODUCT REGISTRATION" },
      { id: 4, title: "SUPPORT" },
      { id: 5, title: "REPAIR" },
      { id: 6, title: "MEDIA" },
      { id: 7, title: "JOBS" },
      { id: 8, title: "CONTACT" },
      { id: 9, title: "PRIVACY POLICY & SMALL PRINT" },
    ],
  },
];

export default NAVIGATION;
